version: '3.4'

networks:
  sqlnetwork:
    driver: bridge

volumes:
  sqldata:

services:

  sql-server:
    image: "mcr.microsoft.com/mssql/server:2017-latest" 
    container_name: sql-server
    ports:
      - "1402:1433"
    networks:
      - sqlnetwork
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=<YourNewStrong@Passw0rd>"
    volumes:
      - sqldata:/var/opt/mssql

  redis-server:
    image: "redis"
    networks:
      - sqlnetwork
    ports:
      - "6379:6379"

  selfhostedodataservice.efcore:
    image: ${DOCKER_REGISTRY-}selfhostedodataservice.efcore
    build:
      context: .
      dockerfile: Samples/OData/SelfHostedODataService.EFCore/Dockerfile
    networks: 
      - sqlnetwork
    environment:
      - "REDISHOST=redis-server"
      - "DBHOST=sql-server"
    ports:
      - 3000:80
      - 5001:443
    depends_on: 
      - sql-server
      - redis-server

  #joker.blazorapp.sample:
  #  image: ${DOCKER_REGISTRY-}jokerblazorappsample
  #  build:
  #    context: .
  #    dockerfile: Samples/Blazor.WebAssembly/Joker.BlazorApp.Sample/Dockerfile
  #  networks: 
  #    - sqlnetwork
  #  depends_on: 
  #    - selfhostedodataservice.efcore
