version: '3.4'

networks:
  sqlnetwork:
    driver: bridge

volumes:
  sqldata:

services:

  sqln:
    image: "mcr.microsoft.com/mssql/server:2017-latest" 
    ports:
      - "1402:1433"
    networks:
      - sqlnetwork
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=<YourNewStrong@Passw0rd>"
    volumes:
      - sqldata:/var/opt/mssql

  redis-server:
    image: "redis"
    networks:
      - sqlnetwork
    ports:
      - "6379:6379"

  selfhostedodataservice:
    image: ${DOCKER_REGISTRY-}selfhostedodataservice
    build:
      context: .
      dockerfile: Samples/OData/SelfHostedODataService/Dockerfile
    networks: 
      - sqlnetwork
    environment:
      - "REDISHOST=redis-server"
      - "DBHOST=sqln"
    ports:
      - 3000:80
      - 5001:443
    depends_on: 
      - sqln
      - redis-server