// <auto-generated />
namespace Sample.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Books_And_Authors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Books_And_Authors));
        
        string IMigrationMetadata.Id
        {
            get { return "202004270626201_Books_And_Authors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
