// <auto-generated />
namespace Sample.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Book_Publisher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Book_Publisher));
        
        string IMigrationMetadata.Id
        {
            get { return "202005031242473_Book_Publisher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
