// <auto-generated />
namespace Sample.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Timestamp_Triggers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Timestamp_Triggers));
        
        string IMigrationMetadata.Id
        {
            get { return "202004091030137_Timestamp_Triggers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
