// <auto-generated />
namespace Sample.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Products_Version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Products_Version));
        
        string IMigrationMetadata.Id
        {
            get { return "202004070702166_Products_Version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
